### ISSUE TITLE
Connection Error (Exception when calling "Connect" with "1" argument: "System error 0x8009030E (No credentials available in the security package)")

### ISSUE THREAD

**Issue by andreaconsadoriw** [zbx-sadman/KSC#1]
Hi,
i try your script and if i well understand i change the value:
if (-Not [string]::IsNullorEmpty($Username))   { $SrvConnectionProps.Add('myuse'       , $Username);   }
if (-Not [string]::IsNullorEmpty($Userpass))   { $SrvConnectionProps.Add('mypass'   , $Userpass);   }
if (-Not [string]::IsNullorEmpty($UserDomain)) { $SrvConnectionProps.Add('mydomain.local' , $UserDomain); }

but if i run the powershell command i get this error output

**Comment by zbx-sadman** [comment]
I made quick look on the Internet and found on Kaspersky Support Site post from one russian user. He wrote that _CoSetProxyBlanket()_ system function calling was help to avoid _System error 0x8009030E_.

I can try to implement it to the PoSh code if you make a testing, because i haven't this error on my system,

**Comment by andreaconsadoriw** [comment]
now is working, was not clear that i've to put -Username and -Userpass in command
